# Generated by Django 3.1.3 on 2020-11-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='queston',
            new_name='question',
        ),
    ]
